steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-pricing-engine', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/django-pricing-engine']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'django-pricing-engine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/django-pricing-engine'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'

images:
  - 'gcr.io/$PROJECT_ID/django-pricing-engine'

options:
  logging: CLOUD_LOGGING_ONLY

